# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20171024_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de In\xedcio'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.TimeField(),
        ),
    ]
