# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20171112_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='atividade',
        ),
        migrations.AddField(
            model_name='comentario',
            name='trabalho_atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='go.TrabalhoAtividade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalhoatividade',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
