# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20171024_1032'),
        ('go', '0005_auto_20171112_1508'),
    ]

    operations = [
    ]
