# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='empresa',
            name='alunos',
            field=models.ManyToManyField(to='go.Usuario'),
        ),
    ]
