# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='media')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Atividade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Empresa')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='trabalhoatividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Usuario'),
        ),
    ]
