# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20171029_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='participantes',
            field=models.ManyToManyField(to='go.Usuario'),
        ),
    ]
