# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_turma_participantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
