# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20171125_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conquistas',
            new_name='Conquista',
        ),
    ]
