# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0005_conquista_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='icone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
