# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0006_auto_20171125_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('pontos_minimos', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='pontos',
        ),
    ]
