# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0007_atividade_data_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Atividade')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Usuario')),
            ],
        ),
    ]
