# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
